config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'posts#index', as: 'home'


  get 'about' => 'pages#about', as: 'about'


  resources :posts do
    resources :comments
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments
  validates :title, presence: true,
                      length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  http_basic_authenticate_with name: "day", password:"123456", only: [:destroy]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy 
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About us'
    @content = 'a sentence string example '
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "day", password:"123456", except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    # render plain: params[:post].inspect 
    @post = Post.new(post_params)

    if(@post.save)
      redirect_to @post #redirect to show view
    else 
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post #redirect to edit view
    else 
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy

    redirect_to posts_path
  end

  #private method with the params the post will take
  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<h3>Comments</h3>
<% @post.comments.each do |comment| %>
  <div class='card border-info mb-3'>
    <p><strong><%= comment.username %></strong>: <%= comment.body%>
    <%= link_to '[X]' , [comment.post, comment], 
      method: :delete,
      data: {confirm: 'Are you sure????' } %></p>
  </div>
<% end %>

app/views/comments/_form.html.erb
<h3>Add Comment</h3>
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username, :class => 'form-control' %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => 'form-control' %>
  </p>
  <p>
    <%= f.submit :class => 'btn btn-info' %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrashCourse</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="navbar-brand"><%= link_to "Post a Post", home_path %>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active nav-link">
        <%= link_to "Home", home_path %>
      </li>
    </ul>

        <ul class="navbar-nav navbar-right">
      <li class="nav-item active nav-link">
        <%= link_to "Create Post", new_post_path %>
      </li>
    </ul>

  </div>
</nav>
  <div class="container">
    <%= yield %>
  </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>

</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>

<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<%# submits to our create method %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %> </div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title, :class => 'form-control' %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body, :class => 'form-control' %>
  </p>

  <p>
    <div class="text-right">
    <%= f.submit :class => 'btn btn-info btn-right' %>
    </div>
  </p>

<% end %>

app/views/posts/index.html.erb
<h1>All blog Posts</h1>
<% @posts.each do |post| %>
  <div class="card card-body text-white bg-primary mb-3">
    <h3 class="card-header"><%= post.title %></h3>
     <div class="card-body">
    <p class="card-text"><%= post.body %></p>
    </div>
    <%= link_to "Read more", post_path(post), :class => 'btn btn-sm btn-light'%>
  </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<h1>Add a post</h1>

<%= form_for :post, url: posts_path do |f| %>
<%# submits to our create method %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger"><%= msg %> </div>
      <% end %>
    <% end %>
  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title, :class => 'form-control' %>
  </p>

  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body, :class => 'form-control' %>
  </p>

  <p>
    <div class="text-right">
    <%= f.submit :class => 'btn btn-info btn-right' %>
    </div>
  </p>

<% end %>

app/views/posts/show.html.erb
<div class='card card-body text-white bg-primary mb-3'>
    <div class="card-header">
      <h2><%= @post.title %></h2>
    </div>
    <div class="card-body">
        <p class="card-text"><%= @post.body %></p>
      </div>
  </div>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-secondary'%>
<%= link_to "Delete", post_path(@post), 
  method: :delete,
  data: {confirm: 'Are you sure?!?!?! this cannot be reversed!!!'},
  :class => 'btn btn-danger'%>

  <hr>

<%= render 'comments/comments' %>
<br>
<%= render 'comments/form' %>